name: scp continuo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copiamos los fichero vía scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/html/"
    - name: Copiar archivos al directorio temporal
      run: |
        mkdir /tmp/archivos-a-copiar
        cp -R . /tmp/archivos-a-copiar
    - name: Kubectl cp
      run: |
        cd /home/k8sergio
        comando="${{ secrets.COMANDO}}"
        bash $comando
      shell: bash

