name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/html/"
    - name: Copiar archivos al directorio temporal
      run: |
        mkdir /tmp/archivos-a-copiar
        cp -R . /tmp/archivos-a-copiar
    - name: Copiar archivos al contenedor de Kubernetes
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'kubectl cp /tmp/archivos-a-copiar https-85c6cdcddd-4h5zc:/usr/local/apache2/htdocs/'
        
