name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/html/"
    - name: Copiar archivos al directorio temporal
      run: |
        mkdir /tmp/archivos-a-copiar
        cp -R . /tmp/archivos-a-copiar
    - name: Kubectl utility
      # You may pin to the exact commit or the version.
      # uses: nickgronow/kubectl@70d7b1dd3e89731270b4760e213fec34fc2659ab
      uses: nickgronow/kubectl@v1.17.4
      with:
      # The kube config data base64 encoded
         config_data: '"${{ secrets.KUBE_CONFIG }}"'
         args: '"kubectl cp /tmp/archivos-a-copiar https-85c6cdcddd-4h5zc:/usr/local/apache2/htdocs/"'
        
