name: scp continuo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copiamos los fichero vía scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/html/"

  creadodir:
    name: creadodir
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Copiar archivos al directorio temporal
      run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }}  "mkdir /tmp/archivos-a-subir"
  
  copiado:
    name: copiado
    needs: creadodir
    runs-on: ubuntu-latest
    steps:
    - name: Subidas al k8s
      run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} ${{ secrets.KUBECTL }}

