name: scp continuo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copiamos los fichero vía scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/html/"
    - name: Copiar archivos al directorio temporal
      run: ${{ secrets.COMANDO1 }} "mkdir /tmp/archivos-a-copiar | cp -R /var/www/html/ /tmp/archivos-a-copiar"


